#!/bin/bash 

#This script will be doing all basic daily git commit


echo "This is your current working files"

#list the modified files in a cleaner way

git status -s

sleep 5

read -p " Do you want to add all changes (y/n) :" RESP

if [ "$RESP" = "y" ]; then
  echo "Changes added"
  echo "Updated the git HEAD"
  
  git add .
else
  echo "Exiting ..."
  sleep 10
  exit;
fi


# read -p 'Enter your commit message' COMMIT
COMMIT=$1

echo "Commit your changes please"
git commit -m $COMMIT

sleep 5 

read -p " Do you want to push the changes (y/n) :" RESPONSE

if [ "$RESPONSE" = "y" ]; then
  echo "Pushing your changes to github"
  echo "Enter your github credentials "
  git push
else
  echo "Sorry but you can use me later"
  echo "exiting ..."
  sleep 6
  exit;
fi
